## settings ##
line-length = 125
indent-width = 4
target-version = "py312"

[format]
docstring-code-format = false   # docstrings not formatted
indent-style = "space"
line-ending = "auto"
quote-style = "single"          # uses single-quotes for strings

[lint.flake8-quotes]
avoid-escape = true             # avoid using backslashes

[lint.isort]
case-sensitive = true

[lint.pycodestyle]
max-line-length = 125

[lint.pydocstyle]
convention = "google"          # short-summary-line, then args-section, then returns-section
